---
- name: Backup MikroTik Configuration
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Run '/export' on MikroTik device
      community.routeros.command:
        commands:
          - /export
      register: mikrotik_config

    - name: Save configuration to a file
      copy:
        content: "{{ mikrotik_config.stdout[0] }}"
        dest: "./backups/{{ inventory_hostname }}_backup.rsc"